# Generated by Django 4.0.4 on 2022-05-11 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='passcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passname_text', models.CharField(max_length=50)),
                ('pass_text', models.CharField(max_length=64)),
            ],
        ),
    ]
